spring:
  # Cấu hình data source cho môi trường local
  datasource:
    url: jdbc:mysql://localhost:5432/mydatabase
    username: secret
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Cấu hình JPA cho môi trường local
  jpa:
    hibernate:
      ddl-auto: validate # Validate khi có flyway
    show-sql: true # Hiển thị câu lệnh SQL trong log để tối ưu khi cần
    properties:
      hibernate:
        format_sql: true # Định dạng câu lệnh SQL cho dễ đọc

  # Cấu hình tự động hỗ trợ docker khi chạy ứng dụng local
  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop # Tự động khởi động và dừng Docker Compose khi ứng dụng chạy và dừng
      file: docker/local/compose.yaml # Đường dẫn đến file Docker Compose cho môi trường local (tính từ thư mục gốc của dự án)

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    from: "noreply@se109.com"

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Xem giá trị truyền vào tham số SQL

springdoc:
  swagger-ui:
    try-it-out-enabled: true
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        # Chỉ expose những gì thực sự cần thiết
        include: health, info, prometheus
  endpoint:
    health:
      show-details: never # Không show chi tiết DB, Disk cho người dùng công cộng, sửa lại when-authorized nếu có security
      probes:
        enabled: true # Bật Liveness và Readiness probes cho Render
    # prometheus:
    #   access: read-only
  metrics:
    tags:
      application: ${spring.application.name} # Lấy tên app tự động
      env: local
    distribution:
      percentiles:
        http:
          server:
            requests:
              - 0.95
              - 0.99 # Định nghĩa percentiles cho tất cả các endpoint HTTP server
      percentiles-histogram:
        http:
          server:
            requests: true # Bật histogram cho tất cả các endpoint HTTP server
      slo:
        http:
          server:
            requests:
              - 100ms
              - 300ms
              - 500ms
              - 1s # Định nghĩa SLO cho các endpoint HTTP server
      maximum-expected-value:
        http:
          server:
            requests: 10s # Giới hạn giá trị tối đa cho histogram để tránh bị ảnh hưởng bởi outliers
      minimum-expected-value:
        http:
          server:
            requests: 10ms # Giới hạn giá trị tối thiểu cho histogram để tránh bị ảnh hưởng bởi outliers

application:
  frontend:
    base-url: http://localhost:3000
  security:
    secret-key: "mySuperSecretKeyForJwtSigningMustBeLongEnoughToSatisfyHS256Requirements"
    access-token-expiration-in-millis: 3600000
    refresh-token-expiration-in-millis: 36000000
    monitoring-secret: Helloworld

loki:
  url: http://localhost:3100/loki/api/v1/push
  username: admin
  password: admin
