application:
  frontend:
    base-url: http://localhost:3000
  security:
    secret-key: "mySuperSecretKeyForJwtSigningMustBeLongEnoughToSatisfyHS256Requirements"
    access-token-expiration-in-millis: 360000
    monitoring-secret: Helloworld

loki:
  url: http://localhost:3100/loki/api/v1/push
  username: loki_user
  password: loki_password

spring:
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    from: "noreply@se109.com"
